#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Downloads Windows 11 from UUP Dump and builds an ISO on Windows.
    Designed for GitHub Actions windows-latest runner.
#>

param(
    [Parameter(Mandatory=$false)]
    [string]$UupSetId = "7f6836ae-9517-4e27-9f76-5823e0b6744c",
    
    [Parameter(Mandatory=$false)]
    [string]$Pack = "zh-cn",
    
    [Parameter(Mandatory=$false)]
    [string]$Edition = "professional%3Bcore",
    
    [Parameter(Mandatory=$false)]
    [string]$OutputIso = "Win11_Source.iso"
)

$ErrorActionPreference = "Stop"
$startTime = Get-Date

Write-Output "=== UUP Dump ISO Downloader for Windows ==="
Write-Output "Set ID: $UupSetId"
Write-Output "Pack: $Pack"
Write-Output "Edition: $Edition"
Write-Output "Output: $OutputIso"

# Step 1: Install aria2c if not present
if (-not (Get-Command aria2c -ErrorAction SilentlyContinue)) {
    Write-Output "Installing aria2c via chocolatey..."
    choco install aria2 -y --no-progress
}

# Step 2: Create directories
New-Item -ItemType Directory -Force -Path "files" | Out-Null
New-Item -ItemType Directory -Force -Path "UUPs" | Out-Null

# Step 3: Download UUP converter (7zr.exe + uup-converter-wimlib.7z)
Write-Output "Downloading UUP converter (7zr.exe)..."
$7zrUrl = "https://uupdump.net/misc/7zr.exe"
$7zrPath = "files\7zr.exe"
aria2c --no-conf --console-log-level=warn -x4 -s4 --allow-overwrite=true --auto-file-renaming=false -d"files" -o"7zr.exe" $7zrUrl
if (-not (Test-Path $7zrPath)) { throw "7zr.exe download failed" }

Write-Output "Downloading uup-converter-wimlib..."
$convUrl = "https://uupdump.net/misc/uup-converter-wimlib-v121.7z"
$convPath = "files\uup-converter-wimlib.7z"
aria2c --no-conf --console-log-level=warn -x4 -s4 --allow-overwrite=true --auto-file-renaming=false -d"files" -o"uup-converter-wimlib.7z" $convUrl
if (-not (Test-Path $convPath)) { throw "uup-converter download failed" }

# Step 4: Extract UUP converter (skip ConvertConfig.ini and CustomAppsList.txt - keep ours)
Write-Output "Extracting UUP converter..."
& $7zrPath -x!ConvertConfig.ini -x!CustomAppsList.txt -y x $convPath
if (-not (Test-Path "convert-UUP.cmd")) { throw "Converter extraction failed - convert-UUP.cmd not found" }

# Step 5: Copy our custom config files
if (Test-Path "ConvertConfig.ini") {
    Write-Output "Using custom ConvertConfig.ini"
}
if (Test-Path "CustomAppsList.txt") {
    Write-Output "Using custom CustomAppsList.txt"
}

# Step 6: Retrieve aria2 script for UUP set
Write-Output "Retrieving aria2 script for UUP set..."
$aria2Script = "aria2_script.$([System.IO.Path]::GetRandomFileName()).txt"
$aria2ScriptUrl = "https://uupdump.net/get.php?id=$UupSetId&pack=$Pack&edition=$Edition&aria2=2"
aria2c --no-conf --console-log-level=warn --allow-overwrite=true --auto-file-renaming=false -o"$aria2Script" $aria2ScriptUrl

# Check for errors
$errorCheck = Select-String -Path $aria2Script -Pattern "#UUPDUMP_ERROR:"
if ($errorCheck) {
    $errMsg = $errorCheck.Line -replace "#UUPDUMP_ERROR:", ""
    throw "UUP Dump Error: $errMsg"
}

# Step 7: Download UUP files
Write-Output "Downloading UUP set (this may take 10-20 minutes)..."
aria2c --no-conf --console-log-level=warn -x16 -s16 -j5 -c -R -d"UUPs" -i"$aria2Script"
Write-Output "UUP download complete!"

# Step 8: Run UUP converter to build ISO
Write-Output "Running UUP converter to build ISO..."
Write-Output "This step builds the full Windows ISO from UUP files."
Write-Output "Expected size: ~4-5GB, time: 10-20 minutes"

# Modify convert-UUP.cmd to not show any prompts
$convCmd = Get-Content "convert-UUP.cmd" -Raw
# The CMD calls convert-UUP.ps1 - make sure it runs without pauses

# Run the converter - it will output an ISO
& cmd.exe /c "convert-UUP.cmd"
$exitCode = $LASTEXITCODE

# Find the generated ISO (it's usually named like 22621.1_MULTI_X64_ZH-CN.ISO or similar)
$generatedIso = Get-ChildItem -Path . -Filter "*.ISO" -ErrorAction SilentlyContinue | Select-Object -First 1

if ($generatedIso) {
    Write-Output "ISO generated: $($generatedIso.Name) ($([math]::Round($generatedIso.Length / 1GB, 2)) GB)"
    if ($generatedIso.Name -ne $OutputIso) {
        Rename-Item -Path $generatedIso.FullName -NewName $OutputIso -Force
        Write-Output "Renamed to: $OutputIso"
    }
} else {
    # Try searching more broadly
    $generatedIso = Get-ChildItem -Path . -Recurse -Filter "*.iso" -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($generatedIso) {
        Write-Output "Found ISO at: $($generatedIso.FullName)"
        Move-Item -Path $generatedIso.FullName -Destination $OutputIso -Force
    } else {
        throw "ISO was not generated by the converter"
    }
}

$elapsed = (Get-Date) - $startTime
Write-Output "=== UUP download and ISO build completed in $($elapsed.TotalMinutes.ToString('F2')) minutes ==="
